### PR TITLE
[BACKLOG-6228] Adding update calculated measure annotation

### PR DESCRIPTION
**Pull request by pminutillo**

### CODE REVIEW

**Comment by bytekast** [comment]
should we change the "visible" property to "hidden"? =)

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/agilebi/modeler/messages/messages_en_US.properties
  src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotation.java
  src/org/pentaho/agilebi/modeler/models/annotations/UpdateCalculatedMember.java
  src/org/pentaho/agilebi/modeler/models/annotations/util/AnnotationConstants.java
  src/org/pentaho/agilebi/modeler/models/annotations/util/MondrianSchemaHandler.java
  test-res/products.with.calc.measures.mondrian.xml
  test-src/org/pentaho/agilebi/modeler/models/annotations/AnnotationUtil.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/CreateCalculatedMemberIT.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotationGroupIT.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/UpdateCalculatedMemberTest.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/util/MondrianSchemaHandlerTest.java






Newly Fixed Tests:
-----------------
org.pentaho.agilebi.modeler.models.annotations.CreateCalculatedMemberIT.testApplyMondrian: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: 
	at org.pentaho.agilebi.modeler.models.annotations.CreateCalculatedMemberIT.testApplyMondrian(CreateCalculatedMemberIT.java:149)

```



Unit test coverage change:
============
org.pentaho.agilebi.modeler.models.annotations.util.MondrianSchemaHandler:
 * instructionPercentCoverageChange : +2.45%
 * branchPercentCoverageChange :**-7.98%**
 * linePercentCoverageChange : +3.24%
 * complexityPercentCoverageChange :**-11.19%**
 * methodPercentCoverageChange : +1.67%
    
org.pentaho.agilebi.modeler.models.annotations.UpdateCalculatedMember:
 * branchPercentCoverage :60.00%
 * linePercentCoverage :84.00%
 * methodPercentCoverage :78.95%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :79.64%
    
org.pentaho.agilebi.modeler.models.annotations.ModelAnnotation.Type:
 * instructionPercentCoverageChange : +0.84%
 * linePercentCoverageChange : +1.08%
    
Integration test coverage change:
============
org.pentaho.agilebi.modeler.models.annotations.util.MondrianSchemaHandler:
 * instructionPercentCoverageChange :**-12.75%**
 * branchPercentCoverageChange :**-17.14%**
 * linePercentCoverageChange :**-13.70%**
 * complexityPercentCoverageChange :**-8.60%**
 * methodPercentCoverageChange :**-2.08%**
    
org.pentaho.agilebi.modeler.models.annotations.ModelAnnotation.Type:
 * instructionPercentCoverageChange : +1.28%
 * linePercentCoverageChange : +1.30%

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/agilebi/modeler/messages/messages_en_US.properties
  src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotation.java
  src/org/pentaho/agilebi/modeler/models/annotations/UpdateCalculatedMember.java
  src/org/pentaho/agilebi/modeler/models/annotations/util/AnnotationConstants.java
  src/org/pentaho/agilebi/modeler/models/annotations/util/MondrianSchemaHandler.java
  test-res/products.with.calc.measures.mondrian.xml
  test-src/org/pentaho/agilebi/modeler/models/annotations/AnnotationUtil.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/CreateCalculatedMemberIT.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotationGroupIT.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/UpdateCalculatedMemberTest.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/util/MondrianSchemaHandlerTest.java






Newly Fixed Tests:
-----------------
org.pentaho.agilebi.modeler.models.annotations.CreateCalculatedMemberIT.testApplyMondrian: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: 
	at org.pentaho.agilebi.modeler.models.annotations.CreateCalculatedMemberIT.testApplyMondrian(CreateCalculatedMemberIT.java:149)

```



Unit test coverage change:
============
org.pentaho.agilebi.modeler.models.annotations.util.MondrianSchemaHandler:
 * instructionPercentCoverageChange : +2.45%
 * branchPercentCoverageChange :**-7.98%**
 * linePercentCoverageChange : +3.24%
 * complexityPercentCoverageChange :**-11.19%**
 * methodPercentCoverageChange : +1.67%
    
org.pentaho.agilebi.modeler.models.annotations.UpdateCalculatedMember:
 * branchPercentCoverage :60.00%
 * linePercentCoverage :84.00%
 * methodPercentCoverage :78.95%
 * complexityPercentCoverage :66.67%
 * instructionPercentCoverage :79.64%
    
org.pentaho.agilebi.modeler.models.annotations.ModelAnnotation.Type:
 * instructionPercentCoverageChange : +0.84%
 * linePercentCoverageChange : +1.08%
    
Integration test coverage change:
============
org.pentaho.agilebi.modeler.models.annotations.util.MondrianSchemaHandler:
 * instructionPercentCoverageChange :**-12.75%**
 * branchPercentCoverageChange :**-17.14%**
 * linePercentCoverageChange :**-13.70%**
 * complexityPercentCoverageChange :**-8.60%**
 * methodPercentCoverageChange :**-2.08%**
    
org.pentaho.agilebi.modeler.models.annotations.ModelAnnotation.Type:
 * instructionPercentCoverageChange : +1.28%
 * linePercentCoverageChange : +1.30%

**Comment by pminutillo** [comment]
Working on some updates

**Pull request closed without merging**
