### PR TITLE
MAVENIZE -- fixing intergation tests

### PR DESCRIPTION
**Pull request by kolinus**

### CODE REVIEW

**Comment by kolinus** [comment]
@jmcnichols18 @smaring fix for ITs

**Comment by rfellows** [comment]
Looks like wingman says there are new tests broken along with some license header issues

**Comment by smaring** [comment]
yeah, but at least this is a large step in the right direction to get the ITs working ... I'm gonna merge and he's gonna keep working on it

**Comment by mdamour1976** [comment]
This pull request has broken downstream unit / integration tests in the pentaho-data-refinery project.

**Pull request merged**
