### PR TITLE
Inline modeling calc measure working remove measure merge

### PR DESCRIPTION
**Pull request by pminutillo**
Added annotation support for adding calculated members to analysis data sources and removing measures

### CODE REVIEW

**Comment by pminutillo** [comment]
@bennychow @dcleao 
Please review and let me know if you have any questions. Thanks!

**Comment by bennychow** [comment]
Hi Peter,
I don't think you need those Enum classes.  Those are specific to Analyzer.  Also, I don't see you handling the format strings for either a regular measure or calculated measure.

**Comment by pminutillo** [comment]
@DFieldFL @bennychow I have made some changes as you suggested. I removed the enum classes from modeler, made the format just a string field on the annotation, and put the logic for resolving the format string in analyzer. Whenever you get a chance, let me know what you think. Thanks!

**Comment by bennychow** [comment]
Looks good.. we'll need to review our annotation interface again soon.  The apply method passes in a field which we don't need to for any of these new model actions.

**Comment by pminutillo** [comment]
@bennychow @DFieldFL @dcleao Additional commit added to incorporate code review feedback. After the review is complete, I'll close this pull request, squash these commits, and send a clean pull request. Please take a look whenever you get a chance.

**Comment by DFieldFL** [comment]
Looks good to me

**Comment by dcleao** [comment]
All looks good. Nothing to add. :-)

**Pull request merged**
