### PR TITLE
Added remove attribute annotation

### PR DESCRIPTION
**Pull request by DFieldFL**
@bennychow @dcleao @pminutillo @bytekast @kurtwalker Any comments would be appreciated. Thank you!

### CODE REVIEW

**Comment by dcleao** [comment]
All well for me!

**Comment by kurtwalker** [comment]
I don't like the "annotation instanceof RemoveAttribute"

Why do fields need to be looked up differently for remove?  any other options for that one?

**Comment by DFieldFL** [comment]
From Analyzer's perspective there could be multiple LevelMetaDatas that point to the same underlying column. The intent is to ensure getting the exact LevelMetaData based on a formula (ex. [PRODUCTNAME.PRODUCTNAME].[PRODUCTNAME]). Analyzer only knows about formulas.

An option is to change the sourceType to "StreamField" or create a different sourceType that just returns the formula rather than doing an instanceof. I would think that changing the sourceType to something else like "RemoveHierarchyLevel" would not be the intent of the sourceType.

Another option is to create a new variable in ModelAnnotation, for example a String form of the annotationType, that can be used by the resolveField method. I am not sure of the code impact of this one.

**Comment by bennychow** [comment]
I think it is time for a refactoring of the ModelAnnotation and AnnotationType sub-classes for 6.0.  When we initially designed the interface for AnnotationType.apply, we always assumed that we were applying a model change using a stream field as the source.  For inline modeling, this is definitely not the case since you could be updating an existing level/measure or deleting a whole dimension/hierarchy.  In both these examples, the source is not a field but a logical model element.  

What we should do is refactor ModelAnnotation so that it no longer tries to pass in the source field to the AnnotationType.apply method.  The source field (or source level or source measure) should be a part of the AnnotationType sub-class itself.  ModelAnnotation.SourceType and ModelAnnotation.resolveField can then be removed.  With this change, ModelAnnotation becomes a very thin wrapper around an AnnotationType instance.  

While we would need to fix the code in SDR, this should not affect the serialization format into the metastore.  There should be no upgrade issues for people who have saved 5.4 model annotation groups into the metastore and then re-open them using a 6.0 client.

**Comment by kurtwalker** [comment]
I agree with Benny.  For the here and now, I don't object to merging the pull request and writing a refactoring case.

**Comment by DFieldFL** [comment]
Thanks for the input. I will squash the commits for this pull request and look at re-factoring for the next annotation as this will be a common thing in the near future.

**Pull request merged**
