### PR TITLE
[BACKLOG-7808] - Unable to clear formatting for zip code

### PR DESCRIPTION
**Pull request by rfellows**

### CODE REVIEW

**Comment by rfellows** [comment]
@kurtwalker please review

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/agilebi/modeler/models/annotations/util/MondrianSchemaHandler.java

Unit test coverage change:
============
org.pentaho.agilebi.modeler.models.annotations.util.MondrianSchemaHandler:
 * Branch Change : **-.66%**
 * Complexity Change : **-1.06%**
 * Instruction Change :  + .02%
 * Line Change :  + .01%

Integration test coverage change:
============
org.pentaho.agilebi.modeler.models.annotations.util.MondrianSchemaHandler:
 * Branch Change : **-1.06%**
 * Complexity Change : **-.74%**
 * Instruction Change : **-.75%**
 * Line Change : **-.56%**

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/src/org/pentaho/agilebi/modeler/models/annotations/util/MondrianSchemaHandler.java

1. Message: '(' is not followed by whitespace. at Line: 644 Column: 66
2. Message: ')' is not preceded with whitespace. at Line: 644 Column: 67
3. Message: '(' is not followed by whitespace. at Line: 645 Column: 17
4. Message: '(' is not followed by whitespace. at Line: 646 Column: 47
5. Message: ')' is not preceded with whitespace. at Line: 646 Column: 93
6. Message: ')' is not preceded with whitespace. at Line: 646 Column: 94
7. Message: ')' is not preceded with whitespace. at Line: 646 Column: 95
8. Message: '(' is not followed by whitespace. at Line: 647 Column: 32
9. Message: ')' is not preceded with whitespace. at Line: 647 Column: 48

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/agilebi/modeler/models/annotations/util/MondrianSchemaHandler.java

Unit test coverage change:
============
org.pentaho.agilebi.modeler.models.annotations.util.MondrianSchemaHandler:
 * Branch Change : **-.66%**
 * Complexity Change : **-1.06%**
 * Instruction Change :  + .02%
 * Line Change :  + .01%

Integration test coverage change:
============
org.pentaho.agilebi.modeler.models.annotations.util.MondrianSchemaHandler:
 * Branch Change : **-1.06%**
 * Complexity Change : **-.74%**
 * Instruction Change : **-.75%**
 * Line Change : **-.56%**

**Comment by lucboudreau** [comment]
0.06% short of a green light. :)

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/agilebi/modeler/models/annotations/util/MondrianSchemaHandler.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/UpdateAttributeTest.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/util/MondrianSchemaHandlerTest.java

Unit test coverage change:
============
org.pentaho.agilebi.modeler.models.annotations.util.MondrianSchemaHandler:
 * Branch Change :  + 1.84%
 * Complexity Change :  + 2.69%
 * Instruction Change :  + .88%
 * Line Change :  + 1.17%

Integration test coverage change:
============
org.pentaho.agilebi.modeler.models.annotations.util.MondrianSchemaHandler:
 * Branch Change : **-1.06%**
 * Complexity Change : **-.74%**
 * Instruction Change : **-.75%**
 * Line Change : **-.56%**

**Pull request merged**
