### PR TITLE
BACKLOG-12127 -- Annotation step incorrectly drops a field when it ha…

### PR DESCRIPTION
**Pull request by kolinus**
…s the

same name as a created measure

What was done:
Added field tracking if the measure is autogenerated or explicitly created
Changed th elogic for removing measures.

### CODE REVIEW

**Comment by kolinus** [comment]
@DFieldFL @kurtwalker could you please review?

**Comment by kurtwalker** [comment]
instead of adding a new property, can we use the memberAnnotations that are already defined for all the model element types?  i.e. measureMetaData.getMemberAnnotations().put(...)

also, need unit tests

**Comment by kolinus** [comment]
@kurtwalker , thank you, it absolutely needs unit test, I was more interested in the approach itself

**Comment by kolinus** [comment]
@kurtwalker actually that map contains member specifi annotations (currently we have just InlineFormatting and GeoRoles ). Shall we create additional dummy annotation?

**Comment by kurtwalker** [comment]
Yes, we'll have to make a new IMemberAnnotation implementation

**Comment by kurtwalker** [comment]
maybe the member annotation should be called something like DefinedBy and we can set it's value to "annotateStream"

**Pull request closed without merging**
