### PR TITLE
[BACKLOG-1531] Update measure aggregation

### PR DESCRIPTION
**Pull request by DFieldFL**
@bennychow @pminutillo @bytekast @kurtwalker please review

### CODE REVIEW

**Comment by pminutillo** [comment]
:star:

**Comment by kurtwalker** [comment]
Would it make sense to have unit tests specific to MondrianSchemaHandler instead of letting the individual annotation tests cover it?

**Comment by DFieldFL** [comment]
@kurtwalker I can do a specific test for the MondrianSchemaHandler if preferred. I will still have to test the annotation which also test that class as well. Seemed like dup code.

**Comment by kurtwalker** [comment]
That's how I would do it and then the annotation test would focus only on the code specifically in that class.  But, I'm fine leaving it.  different styles.

**Comment by DFieldFL** [comment]
I'll work those tests in on the next PR.

**Pull request merged**
