### PR TITLE
[PDB-1427] Default date formats in dashboard and PIR are not same

### PR DESCRIPTION
**Pull request by SergeyTravin**

### CODE REVIEW

**Comment by SergeyTravin** [comment]
@DFieldFL @rfellows @pminutillo could you review it please?

**Comment by DFieldFL** [comment]
@kurtwalker

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.4 -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/agilebi/modeler/ModelerWorkspace.java
  src/org/pentaho/agilebi/modeler/Util.gwt.xml
  src/org/pentaho/agilebi/modeler/gwt/BogoPojo.java
  src/org/pentaho/agilebi/modeler/nodes/BaseAggregationMetaDataNode.java
  src/org/pentaho/agilebi/modeler/propforms/FieldsPropertiesForm.java
  src/org/pentaho/agilebi/modeler/propforms/MeasuresPropertiesForm.java
  src/org/pentaho/agilebi/modeler/res/measuresForm.xul
  src/org/pentaho/agilebi/modeler/res/reportingForms.xul
  src/org/pentaho/agilebi/modeler/util/DataFormatHolder.java
  test-src/org/pentaho/agilebi/modeler/ModelerWorkspaceTest.java


Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards

File src/org/pentaho/agilebi/modeler/gwt/BogoPojo.java
1. Message: Line has trailing spaces at Line: 103 Column: None

File src/org/pentaho/agilebi/modeler/nodes/BaseAggregationMetaDataNode.java
1. Message: Line has trailing spaces at Line: 205 Column: None
2. Message: Line has trailing spaces at Line: 210 Column: None
3. Message: Line has trailing spaces at Line: 212 Column: None
4. Message: Line has trailing spaces at Line: 54 Column: None
5. Message: Line has trailing spaces at Line: 55 Column: None

File src/org/pentaho/agilebi/modeler/propforms/MeasuresPropertiesForm.java
1. Message: Line has trailing spaces at Line: 117 Column: None
2. Message: Line has trailing spaces at Line: 66 Column: None

File src/org/pentaho/agilebi/modeler/util/DataFormatHolder.java
1. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 100 Column: None
2. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 100 Column: None
3. Message: 'block rcurly' have incorrect indentation level 2, expected level should be one of the following: 4, 6. at Line: 101 Column: None
4. Message: '}' is not followed by whitespace. at Line: 101 Column: 4
5. Message: '}' is not preceded with whitespace. at Line: 101 Column: 4
6. Message: Line has trailing spaces at Line: 102 Column: None
7. Message: Line has trailing spaces at Line: 24 Column: None
8. Message: '{' is not followed by whitespace. at Line: 25 Column: 69
9. Message: '{' is not preceded with whitespace. at Line: 25 Column: 68
10. Message: '{' is not preceded with whitespace. at Line: 25 Column: 69
11. Message: ')' is not preceded with whitespace. at Line: 26 Column: 20
12. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 26 Column: None
13. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 26 Column: None
14. Message: ')' is not preceded with whitespace. at Line: 27 Column: 20
15. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 27 Column: None
16. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 27 Column: None
17. Message: ')' is not preceded with whitespace. at Line: 28 Column: 22
18. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 28 Column: None
19. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 28 Column: None
20. Message: ')' is not preceded with whitespace. at Line: 29 Column: 20
21. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 29 Column: None
22. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 29 Column: None
23. Message: ')' is not preceded with whitespace. at Line: 30 Column: 22
24. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 30 Column: None
25. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 30 Column: None
26. Message: ')' is not preceded with whitespace. at Line: 31 Column: 20
27. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 31 Column: None
28. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 31 Column: None
29. Message: ')' is not preceded with whitespace. at Line: 32 Column: 22
30. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 32 Column: None
31. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 32 Column: None
32. Message: ')' is not preceded with whitespace. at Line: 33 Column: 22
33. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 33 Column: None
34. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 33 Column: None
35. Message: ')' is not preceded with whitespace. at Line: 34 Column: 22
36. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 34 Column: None
37. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 34 Column: None
38. Message: ')' is not preceded with whitespace. at Line: 35 Column: 22
39. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 35 Column: None
40. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 35 Column: None
41. Message: ')' is not preceded with whitespace. at Line: 36 Column: 23
42. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 36 Column: None
43. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 36 Column: None
44. Message: ')' is not preceded with whitespace. at Line: 37 Column: 24
45. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 37 Column: None
46. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 37 Column: None
47. Message: ')' is not preceded with whitespace. at Line: 38 Column: 24
48. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 38 Column: None
49. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 38 Column: None
50. Message: ')' is not preceded with whitespace. at Line: 39 Column: 25
51. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 39 Column: None
52. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 39 Column: None
53. Message: ')' is not preceded with whitespace. at Line: 40 Column: 26
54. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 40 Column: None
55. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 40 Column: None
56. Message: ')' is not preceded with whitespace. at Line: 41 Column: 28
57. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 41 Column: None
58. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 41 Column: None
59. Message: ')' is not preceded with whitespace. at Line: 42 Column: 26
60. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 42 Column: None
61. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 42 Column: None
62. Message: ')' is not preceded with whitespace. at Line: 43 Column: 28
63. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 43 Column: None
64. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 43 Column: None
65. Message: ')' is not preceded with whitespace. at Line: 44 Column: 26
66. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 44 Column: None
67. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 44 Column: None
68. Message: ')' is not preceded with whitespace. at Line: 45 Column: 28
69. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 45 Column: None
70. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 45 Column: None
71. Message: ')' is not preceded with whitespace. at Line: 46 Column: 28
72. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 46 Column: None
73. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 46 Column: None
74. Message: ')' is not preceded with whitespace. at Line: 47 Column: 28
75. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 47 Column: None
76. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 47 Column: None
77. Message: ')' is not preceded with whitespace. at Line: 48 Column: 28
78. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 48 Column: None
79. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 48 Column: None
80. Message: ')' is not preceded with whitespace. at Line: 49 Column: 29
81. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 49 Column: None
82. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 49 Column: None
83. Message: ')' is not preceded with whitespace. at Line: 50 Column: 30
84. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 50 Column: None
85. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 50 Column: None
86. Message: ')' is not preceded with whitespace. at Line: 51 Column: 26
87. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 51 Column: None
88. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 51 Column: None
89. Message: ')' is not preceded with whitespace. at Line: 52 Column: 27
90. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 52 Column: None
91. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 52 Column: None
92. Message: ')' is not preceded with whitespace. at Line: 53 Column: 29
93. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 53 Column: None
94. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 53 Column: None
95. Message: ')' is not preceded with whitespace. at Line: 54 Column: 31
96. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 54 Column: None
97. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 54 Column: None
98. Message: ')' is not preceded with whitespace. at Line: 55 Column: 29
99. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 55 Column: None
100. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 55 Column: None
101. Message: ')' is not preceded with whitespace. at Line: 56 Column: 31
102. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 56 Column: None
103. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 56 Column: None
104. Message: ')' is not preceded with whitespace. at Line: 57 Column: 29
105. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 57 Column: None
106. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 57 Column: None
107. Message: ')' is not preceded with whitespace. at Line: 58 Column: 31
108. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 58 Column: None
109. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 58 Column: None
110. Message: ')' is not preceded with whitespace. at Line: 59 Column: 31
111. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 59 Column: None
112. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 59 Column: None
113. Message: ')' is not preceded with whitespace. at Line: 60 Column: 31
114. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 60 Column: None
115. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 60 Column: None
116. Message: ')' is not preceded with whitespace. at Line: 61 Column: 31
117. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 61 Column: None
118. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 61 Column: None
119. Message: ')' is not preceded with whitespace. at Line: 62 Column: 32
120. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 62 Column: None
121. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 62 Column: None
122. Message: ')' is not preceded with whitespace. at Line: 63 Column: 33
123. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 63 Column: None
124. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 63 Column: None
125. Message: ')' is not preceded with whitespace. at Line: 64 Column: 31
126. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 64 Column: None
127. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 64 Column: None
128. Message: ')' is not preceded with whitespace. at Line: 65 Column: 33
129. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 65 Column: None
130. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 65 Column: None
131. Message: ')' is not preceded with whitespace. at Line: 66 Column: 31
132. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 66 Column: None
133. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 66 Column: None
134. Message: ')' is not preceded with whitespace. at Line: 67 Column: 33
135. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 67 Column: None
136. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 67 Column: None
137. Message: ')' is not preceded with whitespace. at Line: 68 Column: 31
138. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 68 Column: None
139. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 68 Column: None
140. Message: ')' is not preceded with whitespace. at Line: 69 Column: 33
141. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 69 Column: None
142. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 69 Column: None
143. Message: ')' is not preceded with whitespace. at Line: 70 Column: 33
144. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 70 Column: None
145. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 70 Column: None
146. Message: ')' is not preceded with whitespace. at Line: 71 Column: 33
147. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 71 Column: None
148. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 71 Column: None
149. Message: ')' is not preceded with whitespace. at Line: 72 Column: 33
150. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 72 Column: None
151. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 72 Column: None
152. Message: ')' is not preceded with whitespace. at Line: 73 Column: 34
153. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 73 Column: None
154. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 73 Column: None
155. Message: ')' is not preceded with whitespace. at Line: 74 Column: 35
156. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 74 Column: None
157. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 74 Column: None
158. Message: ')' is not preceded with whitespace. at Line: 75 Column: 33
159. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 75 Column: None
160. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 75 Column: None
161. Message: ')' is not preceded with whitespace. at Line: 76 Column: 35
162. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 76 Column: None
163. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 76 Column: None
164. Message: ')' is not preceded with whitespace. at Line: 77 Column: 33
165. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 77 Column: None
166. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 77 Column: None
167. Message: ')' is not preceded with whitespace. at Line: 78 Column: 35
168. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 78 Column: None
169. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 78 Column: None
170. Message: ')' is not preceded with whitespace. at Line: 79 Column: 33
171. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 79 Column: None
172. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 79 Column: None
173. Message: ')' is not preceded with whitespace. at Line: 80 Column: 35
174. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 80 Column: None
175. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 80 Column: None
176. Message: ')' is not preceded with whitespace. at Line: 81 Column: 35
177. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 81 Column: None
178. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 81 Column: None
179. Message: ')' is not preceded with whitespace. at Line: 82 Column: 35
180. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 82 Column: None
181. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 82 Column: None
182. Message: ')' is not preceded with whitespace. at Line: 83 Column: 35
183. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 83 Column: None
184. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 83 Column: None
185. Message: ')' is not preceded with whitespace. at Line: 84 Column: 36
186. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 84 Column: None
187. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 84 Column: None
188. Message: ')' is not preceded with whitespace. at Line: 85 Column: 37
189. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 85 Column: None
190. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 85 Column: None
191. Message: 'block rcurly' have incorrect indentation level 2, expected level should be one of the following: 4, 6. at Line: 86 Column: None
192. Message: '}' is not followed by whitespace. at Line: 86 Column: 4
193. Message: '}' is not preceded with whitespace. at Line: 86 Column: 4
194. Message: Line has trailing spaces at Line: 87 Column: None
195. Message: '{' is not followed by whitespace. at Line: 88 Column: 71
196. Message: '{' is not preceded with whitespace. at Line: 88 Column: 70
197. Message: '{' is not preceded with whitespace. at Line: 88 Column: 71
198. Message: ')' is not preceded with whitespace. at Line: 89 Column: 16
199. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 89 Column: None
200. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 89 Column: None
201. Message: ')' is not preceded with whitespace. at Line: 90 Column: 25
202. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 90 Column: None
203. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 90 Column: None
204. Message: ')' is not preceded with whitespace. at Line: 91 Column: 15
205. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 91 Column: None
206. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 91 Column: None
207. Message: ')' is not preceded with whitespace. at Line: 92 Column: 13
208. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 92 Column: None
209. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 92 Column: None
210. Message: ')' is not preceded with whitespace. at Line: 93 Column: 25
211. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 93 Column: None
212. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 93 Column: None
213. Message: ')' is not preceded with whitespace. at Line: 94 Column: 23
214. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 94 Column: None
215. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 94 Column: None
216. Message: ')' is not preceded with whitespace. at Line: 95 Column: 22
217. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 95 Column: None
218. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 95 Column: None
219. Message: 'block rcurly' have incorrect indentation level 2, expected level should be one of the following: 4, 6. at Line: 96 Column: None
220. Message: '}' is not followed by whitespace. at Line: 96 Column: 4
221. Message: '}' is not preceded with whitespace. at Line: 96 Column: 4
222. Message: Line has trailing spaces at Line: 97 Column: None
223. Message: '{' is not followed by whitespace. at Line: 98 Column: 75
224. Message: '{' is not preceded with whitespace. at Line: 98 Column: 74
225. Message: '{' is not preceded with whitespace. at Line: 98 Column: 75
226. Message: 'block' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 99 Column: None
227. Message: 'method call' child have incorrect indentation level 4, expected level should be one of the following: 6, 8. at Line: 99 Column: None

File test-src/org/pentaho/agilebi/modeler/ModelerWorkspaceTest.java
1. Message: Line has trailing spaces at Line: 101 Column: None
2. Message: Line has trailing spaces at Line: 104 Column: None
3. Message: Unused import - org.mockito.Spy. at Line: 23 Column: 8
4. Message: Using a static member import should be avoided - junit.framework.Assert.*. at Line: 57 Column: None
5. Message: Line has trailing spaces at Line: 89 Column: None
6. Message: Line has trailing spaces at Line: 94 Column: None
7. Message: Line has trailing spaces at Line: 98 Column: None









Unit test coverage change:
============
org.pentaho.agilebi.modeler.nodes.BaseAggregationMetaDataNode:
 * instructionPercentCoverageChange : +1.85%
 * branchPercentCoverageChange : +4.55%
 * linePercentCoverageChange : +3.48%
 * complexityPercentCoverageChange : +9.04%
 * methodPercentCoverageChange : +7.25%
    
org.pentaho.agilebi.modeler.util.DataFormatHolder.new ArrayList() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.agilebi.modeler.util.DataFormatHolder:
 * linePercentCoverage :75.00%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :81.25%
    
org.pentaho.agilebi.modeler.nodes.FieldMetaData:
 * instructionPercentCoverageChange : +9.30%
 * branchPercentCoverageChange : +10.00%
 * linePercentCoverageChange : +8.33%
 * complexityPercentCoverageChange : +7.14%
    
org.pentaho.agilebi.modeler.ModelerWorkspace:
 * instructionPercentCoverageChange : +1.62%
 * branchPercentCoverageChange : +0.29%
 * linePercentCoverageChange : +1.33%
 * complexityPercentCoverageChange : +0.53%
 * methodPercentCoverageChange : +1.14%
    
org.pentaho.agilebi.modeler.ModelerWorkspace.new Object() {...}:
 * instructionPercentCoverageChange :**-2.22%**
    
Integration test coverage change:
============
org.pentaho.agilebi.modeler.util.DataFormatHolder:
 * linePercentCoverage :75.00%
 * methodPercentCoverage :50.00%
 * complexityPercentCoverage :50.00%
 * instructionPercentCoverage :81.25%
    
org.pentaho.agilebi.modeler.ModelerWorkspace:
 * instructionPercentCoverageChange : +0.40%
 * branchPercentCoverageChange : +0.52%
 * linePercentCoverageChange : +0.60%
 * complexityPercentCoverageChange : +0.37%
    
org.pentaho.agilebi.modeler.nodes.BaseAggregationMetaDataNode:
 * instructionPercentCoverageChange :**-0.25%**
 * linePercentCoverageChange :**-0.01%**
 * complexityPercentCoverageChange :**-0.16%**
 * methodPercentCoverageChange :**-2.28%**
    
org.pentaho.agilebi.modeler.util.DataFormatHolder.new ArrayList() {...}:
 * linePercentCoverage :100.00%
 * methodPercentCoverage :100.00%
 * complexityPercentCoverage :100.00%
 * instructionPercentCoverage :100.00%
    
org.pentaho.agilebi.modeler.ModelerWorkspace.new Object() {...}:
 * instructionPercentCoverageChange :**-2.22%**

**Comment by pamval** [comment]
@SergeyTravin you need to review check style for these files

**Comment by lucboudreau** [comment]
@kurtwalker @SergeyTravin You guys jumped the gun on this one. There are a lot of checkstyle issues.

**Comment by kurtwalker** [comment]
I know, forgot to wait for wingman.

**Comment by SergeyTravin** [comment]
https://github.com/pentaho/modeler/pull/268

**Comment by SergeyTravin** [comment]
fix for checkstyle
https://github.com/pentaho/modeler/pull/269

**Pull request merged**
