### PR TITLE
[BACKLOG-3859] Add format to Update measure annotation

### PR DESCRIPTION
**Pull request by DFieldFL**

### CODE REVIEW

**Comment by DFieldFL** [comment]
@bytekast @pminutillo @kurtwalker @bennychow @kolinus Please review

@kurtwalker added tests for MondrianSchemaHandler

@bytekast removed ModelProperty annotation from measure attribute so it doesn't appear in the annotation xml. Will need to think of an easy way to add this value to the modelannotation xml.

**Comment by bytekast** [comment]
@DFieldFL why don't you want it to appear in the xml?

**Comment by DFieldFL** [comment]
@bytekast and I had a side conversation. I think we are good for now.

**Comment by bennychow** [comment]
Looks good to me.

**Pull request merged**
