### PR TITLE
[BACKLOG-4971] Set empty hierarchy to dimension name on apply

### PR DESCRIPTION
**Pull request by bytekast**

### CODE REVIEW

**Comment by bytekast** [comment]
@kurtwalker @pminutillo @DFieldFL - please review

**Comment by kurtwalker** [comment]
what's up with the extra merge commit?

**Comment by bytekast** [comment]
I was working on a feature branch. When I pulled from upstream master, it created an empty merge commit for some reason...

**Comment by kurtwalker** [comment]
any way to clean it up? doesn't look empty when you go into the commit.

**Comment by bytekast** [comment]
Hmm.. Let me see...

**Comment by bytekast** [comment]
will close this and open a new one

**Pull request closed without merging**
