### PR TITLE
[BACKLOG-4900] DSW - After editing automated DS Model Editor hangs wh…

### PR DESCRIPTION
**Pull request by annapopova1**
…en closing.

Added checking empty list "existingCubes" to avoid IndexOfBoundsException. This is the reason of hang popup.

@plagoa @diogofscmariano @rfellows @krivera-pentaho @scottyaslan @pamval please review

### CODE REVIEW

**Comment by diogofscmariano** [comment]
@annapopova1 shouldn't we add unit tests?

**Comment by annapopova1** [comment]
@kurtwalker take a look please because initially this is your code.
I'll add unit test if it's needed.

**Comment by kurtwalker** [comment]
looks good, unit test would be great.  Thanks.

**Comment by plagoa** [comment]
@kurtwalker please check this PR that contains Anna's changes and the unit test: https://github.com/pentaho/modeler/pull/231

**Comment by krivera-pentaho** [comment]
this change was made in #231

**Pull request closed without merging**
