### PR TITLE
CLEANUP-- changing tests to see sonar reaction

### PR DESCRIPTION
**Pull request by kolinus**
What was done:
additional branch of code covered with test.

### CODE REVIEW

**Comment by kolinus** [comment]
@rfellows @kurtwalker could you please check in? it is test to change number of branches covered to see if Sonar notices it

**Comment by kurtwalker** [comment]
are there some files missing from this commit?

**Comment by kolinus** [comment]
no it is wingman issue, no issue when building it locally  mvn clean install -DrunITs

**Comment by kurtwalker** [comment]
I mean that you've added a single assert, but your comment suggests you're covering more branches.  I don't follow how that's the case

**Comment by lucboudreau** [comment]
> no it is wingman issue

Please share what the issue is so that we can fix it.

**Comment by kolinus** [comment]
my comment says about one branch.
this is covered by the assert because one of the "if" was never tested :)
actually this is reflected in tests results
org.pentaho.agilebi.modeler.models.JoinTableModel

    Branch Change: + 25.00%
    Complexity Change: + 10.00%
    Instruction Change: + 2.90%
    Line Change: + 4.55%

**Comment by rfellows** [comment]
@smaring is still working on getting the correct sonar parameters set in the cerberus job(s) to publish the coverage results to sonar. this change will not hit sonar unless that happens first

**Pull request merged**
