### PR TITLE
[BACKLOG-4341] - removing visibility toggeling.

### PR DESCRIPTION
**Pull request by kurtwalker**
@rfellows @pentaho-nbaker super low priority.  I can't even really explain why this fixes the issue.  I spent most of yesterday looking for any differences in behavior with this change (other than fixing the bug) and found nothing.  You guys were the last ones in here.....4 years ago.  So, ya, review at your leisure.

### CODE REVIEW

**Comment by rfellows** [comment]
wow, i agree in that i have no idea how or why that would fix that bug. The question i have is what else is that messageBox used for? i can't imagine that it's there for no reason. I think that class is extended by others, how does this affect them?

If i remember correctly, the messageBox vbox is just a container wrapping the label that shows the messages if something in the model is out of whack. It is used to control whether or not you can see that label. by removing that check, is that label always visible now, even if no issues are found?

**Comment by kurtwalker** [comment]
I thought that would happen too, but after the change, no messages when the model is good.  messages show up when the model is bad.

**Comment by kurtwalker** [comment]
only other usage of the form I found was in data-access, so I checked the model editor in PUC too.  no change that I saw

**Comment by rfellows** [comment]
ok, as long as it's all working still. 

strange though.

**Pull request merged**
