### PR TITLE
Sp 3406

### PR DESCRIPTION
**Pull request by ivanpogodin**

### CODE REVIEW

**Comment by ivanpogodin** [comment]
@mbatchelor, @duarteteixeira , could you review it, please?

**Comment by ivanpogodin** [comment]
@mbatchelor, @duarteteixeira , could you review it, please?

**Comment by mchen-len-son** [comment]
@mbatchelor @pamval @duarteteixeira can you please take a look?

This is a backport of #324.

Thanks.

**Comment by mchen-len-son** [comment]
@mbatchelor @pamval @duarteteixeira can you please take a look?
thanks.

**Pull request merged**
