### PR TITLE
MAVENIZATION

### PR DESCRIPTION
**Pull request by kolinus**
What was done:
Separated code into modules

### CODE REVIEW

**Comment by kolinus** [comment]
@rfellows @kurtwalker @jmcnichols18 @smaring , updated PR for mavenization addressing data rfinery test issues and introducing separation code to modules

**Comment by kolinus** [comment]
all the IT tests pass locally, any way to retriger wingman ?

**Comment by mdamour1976** [comment]
@lucboudreau can you re-trigger wingman on this one?

**Comment by lucboudreau** [comment]
@mdamour1976 I can, but I'm pretty sure it will fail. Wingman won't be able to compare a maven and an ant build. The files won't be in the same place, and it will get confused when guessing which build tool to invoke.

**Comment by mdamour1976** [comment]
@lucboudreau that was my fear also :(  It should pass on the tests though.  I haven't tried locally.  My selfish interest in this case has to do with downstream issues in SDR.

**Comment by kolinus** [comment]
@lucboudreau actually we had sucessfull builds of mavenized modeller. this PR is just about restructuring the things and separating them to modules. am I mising something

**Comment by lucboudreau** [comment]
@kolinus I meant maybe not to rely on Wingman for this one at all. I'm sure that enough people have tested this locally by now.

**Comment by rfellows** [comment]
I can't successfully build this branch. I think the modules are out of order or something

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Pentaho Community Edition Project: pentaho-modeler . FAILURE [ 11.732 s]
[INFO] Pentaho Community Edition Project: pentaho-modeler-client SKIPPED
[INFO] Pentaho Community Edition Project: pentaho-modeler-xul SKIPPED
[INFO] Pentaho Community Edition Project: pentaho-modeler-gwt SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.911 s
[INFO] Finished at: 2016-08-16T13:47:52-04:00
[INFO] Final Memory: 22M/225M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack (unpack-modules) on project pentaho-modeler: Unable to find artifact. Could not find artifact pentaho:pentaho-modeler-xul:jar:7.0-SNAPSHOT in pentaho-repo (http://nexus.pentaho.org/content/groups/omni)
```

Looks like the root/parent depends on the xul submodule. probably need to create another 'core' submodule that contains the code that is currently in the root. let the root just control the module build order.

**Comment by kolinus** [comment]
@rfellows has updated this one

**Comment by kolinus** [comment]
@smaring  @jmcnichols18  this change contains code separation to modules. the binaries zip are now build by assemblies submodule. also assembly builds pentaho-modeler jar but I'm not sure it is published, so there possible downstream failures. There was a test build for another branch from my fork. Can it be recongigured to current branch so all the downstream dependant projects can be found?

**Comment by rfellows** [comment]
The one "Newly Broken" test isn't failing for me either.

There is one checkstyle violation however. Can you take care of that one?

**Pull request merged**
