### PR TITLE
[BACKLOG-7852] - CreateAttribute support for format string

### PR DESCRIPTION
**Pull request by kurtwalker**

### CODE REVIEW

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/agilebi/modeler/geo/GeoRole.java
  src/org/pentaho/agilebi/modeler/models/annotations/CreateAttribute.java
  src/org/pentaho/agilebi/modeler/models/annotations/ModelProperty.java
  src/org/pentaho/agilebi/modeler/models/annotations/data/InlineFormatAnnotation.java
  src/org/pentaho/agilebi/modeler/nodes/annotations/AnalyzerDateFormatAnnotation.java
  src/org/pentaho/agilebi/modeler/nodes/annotations/IMemberAnnotation.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/CreateAttributeIT.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/data/InlineFormatAnnotationTest.java

Unit test coverage change:
============
org.pentaho.agilebi.modeler.geo.GeoRole:
 * Instruction Change :  + .24%
 * Line Change :  + .34%

org.pentaho.agilebi.modeler.models.annotations.CreateAttribute:
 * Branch Change :  + .44%
 * Complexity Change : **-.19%**
 * Instruction Change : **-.30%**
 * Line Change : **-.55%**
 * Method Change : **-1.24%**

org.pentaho.agilebi.modeler.models.annotations.data.InlineFormatAnnotation:
 * Complexity New Coverage : 37.50%
 * Instruction New Coverage : 76.92%
 * Line New Coverage : 58.33%
 * Method New Coverage : 37.50%

org.pentaho.agilebi.modeler.models.annotations.ModelProperty.AppliesTo:
 * Complexity New Coverage : 75.00%
 * Instruction New Coverage : 89.58%
 * Line New Coverage : 100.00%
 * Method New Coverage : 75.00%

Integration test coverage change:
============
org.pentaho.agilebi.modeler.geo.GeoRole:
 * Instruction Change : **-.16%**
 * Line Change : **-.26%**

org.pentaho.agilebi.modeler.models.annotations.CreateAttribute:
 * Branch Change :  + .25%
 * Complexity Change :  + .41%
 * Instruction Change :  + .21%
 * Line Change :  + .31%
 * Method Change :  + .24%

org.pentaho.agilebi.modeler.models.annotations.data.InlineFormatAnnotation:
 * Complexity New Coverage : 62.50%
 * Instruction New Coverage : 79.49%
 * Line New Coverage : 83.33%
 * Method New Coverage : 62.50%

org.pentaho.agilebi.modeler.models.annotations.ModelProperty.AppliesTo:
 * Complexity New Coverage : 75.00%
 * Instruction New Coverage : 89.58%
 * Line New Coverage : 100.00%
 * Method New Coverage : 75.00%

org.pentaho.agilebi.modeler.nodes.annotations.AnalyzerDateFormatAnnotation:
 * Instruction Change : **-.33%**
 * Line Change : **-.39%**

License header violations:
==========================
1. Copyright year is not the current year on src/org/pentaho/agilebi/modeler/models/annotations/ModelProperty.java. Found 2014. Was expecting 2016
2. Copyright year is not the current year on test-src/org/pentaho/agilebi/modeler/models/annotations/CreateAttributeIT.java. Found 2014. Was expecting 2016

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/src/org/pentaho/agilebi/modeler/models/annotations/CreateAttribute.java

1. Message: Using a static member import should be avoided - org.pentaho.di.core.Const.isEmpty. at Line: 48

File /home/buildguy/project/test-src/org/pentaho/agilebi/modeler/models/annotations/CreateAttributeIT.java

1. Message: Using a static member import should be avoided - junit.framework.Assert.assertEquals. at Line: 25
2. Message: Using a static member import should be avoided - junit.framework.Assert.assertFalse. at Line: 26
3. Message: Using a static member import should be avoided - junit.framework.Assert.assertNotNull. at Line: 27
4. Message: Using a static member import should be avoided - junit.framework.Assert.assertTrue. at Line: 28
5. Message: Using a static member import should be avoided - junit.framework.Assert.fail. at Line: 29
6. Message: Using a static member import should be avoided - org.pentaho.agilebi.modeler.models.annotations.CreateAttribute.*. at Line: 30

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/agilebi/modeler/geo/GeoRole.java
  src/org/pentaho/agilebi/modeler/models/annotations/CreateAttribute.java
  src/org/pentaho/agilebi/modeler/models/annotations/ModelProperty.java
  src/org/pentaho/agilebi/modeler/models/annotations/data/InlineFormatAnnotation.java
  src/org/pentaho/agilebi/modeler/nodes/annotations/AnalyzerDateFormatAnnotation.java
  src/org/pentaho/agilebi/modeler/nodes/annotations/IMemberAnnotation.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/CreateAttributeIT.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/data/InlineFormatAnnotationTest.java

Unit test coverage change:
============
org.pentaho.agilebi.modeler.geo.GeoRole:
 * Instruction Change :  + .24%
 * Line Change :  + .34%

org.pentaho.agilebi.modeler.models.annotations.CreateAttribute:
 * Branch Change :  + .44%
 * Complexity Change : **-.19%**
 * Instruction Change : **-.30%**
 * Line Change : **-.55%**
 * Method Change : **-1.24%**

org.pentaho.agilebi.modeler.models.annotations.data.InlineFormatAnnotation:
 * Complexity New Coverage : 37.50%
 * Instruction New Coverage : 76.92%
 * Line New Coverage : 58.33%
 * Method New Coverage : 37.50%

org.pentaho.agilebi.modeler.models.annotations.ModelProperty.AppliesTo:
 * Complexity New Coverage : 75.00%
 * Instruction New Coverage : 89.58%
 * Line New Coverage : 100.00%
 * Method New Coverage : 75.00%

Integration test coverage change:
============
org.pentaho.agilebi.modeler.geo.GeoRole:
 * Instruction Change : **-.16%**
 * Line Change : **-.26%**

org.pentaho.agilebi.modeler.models.annotations.CreateAttribute:
 * Branch Change :  + .25%
 * Complexity Change :  + .41%
 * Instruction Change :  + .21%
 * Line Change :  + .31%
 * Method Change :  + .24%

org.pentaho.agilebi.modeler.models.annotations.data.InlineFormatAnnotation:
 * Complexity New Coverage : 62.50%
 * Instruction New Coverage : 79.49%
 * Line New Coverage : 83.33%
 * Method New Coverage : 62.50%

org.pentaho.agilebi.modeler.models.annotations.ModelProperty.AppliesTo:
 * Complexity New Coverage : 75.00%
 * Instruction New Coverage : 89.58%
 * Line New Coverage : 100.00%
 * Method New Coverage : 75.00%

org.pentaho.agilebi.modeler.nodes.annotations.AnalyzerDateFormatAnnotation:
 * Instruction Change : **-.33%**
 * Line Change : **-.39%**

Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/src/org/pentaho/agilebi/modeler/models/annotations/CreateAttribute.java

1. Message: Using a static member import should be avoided - org.pentaho.di.core.Const.isEmpty. at Line: 48

File /home/buildguy/project/test-src/org/pentaho/agilebi/modeler/models/annotations/CreateAttributeIT.java

1. Message: Using a static member import should be avoided - junit.framework.Assert.assertEquals. at Line: 25
2. Message: Using a static member import should be avoided - junit.framework.Assert.assertFalse. at Line: 26
3. Message: Using a static member import should be avoided - junit.framework.Assert.assertNotNull. at Line: 27
4. Message: Using a static member import should be avoided - junit.framework.Assert.assertTrue. at Line: 28
5. Message: Using a static member import should be avoided - junit.framework.Assert.fail. at Line: 29
6. Message: Using a static member import should be avoided - org.pentaho.agilebi.modeler.models.annotations.CreateAttribute.*. at Line: 30

**Comment by kurtwalker** [comment]
@DFieldFL @rfellows @pminutillo please review

**Comment by kurtwalker** [comment]
@pminutillo @DFieldFL @rfellows

**Pull request merged**
