### PR TITLE
[ANALYZER-3430] Calculated measure created using inline modeling feature in Analyzer is saved on a different cube than where it was created

### PR DESCRIPTION
**Pull request by Advent51**
-fixed

### CODE REVIEW

**Comment by Advent51** [comment]
@rfellows please review

**Comment by kurtwalker** [comment]
Having Cube be a requirement will cause existing calc measure annotations to fail.  We should fall back to choosing whichever cube we were using before when it wasn't specified.

**Comment by Advent51** [comment]
@kurtwalker Well, I tried to use old calc measures on the server, after applying this fix, and they were loaded and worked properly. I checked it with new analyzer report in PUC. Also they (old measures) are exported without "cube"-property like it was before.
Need I check something else?

**Comment by kurtwalker** [comment]
ok, I was assuming the validate would stop it from working.   We should still not require that cube is set, just let it be optional.  In Annotate Stream the same code is used, and the user would typically not know the cube name at that time.  In fact since there is always only one cube with Annotate Stream, we should hide the cube property from the pdi UI using "hideUI = true" in the ModelProperty annotation

**Comment by Advent51** [comment]
@kurtwalker Ok, I get it now. Thanks for explanation. Please review this fix.

**Pull request merged**
