### PR TITLE
[BACKLOG-5768] Add hidden attribute to Measure and Level

### PR DESCRIPTION
**Pull request by bytekast**

### CODE REVIEW

**Comment by bytekast** [comment]
@bennychow @rfellows @kurtwalker - please review

**Comment by rfellows** [comment]
Looks good to me.

**Comment by bennychow** [comment]
Looks good to me too.

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/agilebi/modeler/BaseModelerWorkspaceHelper.java
  src/org/pentaho/agilebi/modeler/models/annotations/CreateAttribute.java
  src/org/pentaho/agilebi/modeler/models/annotations/CreateMeasure.java
  src/org/pentaho/agilebi/modeler/nodes/BaseColumnBackedMetaData.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/CreateAttributeIT.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/CreateMeasureTest.java




Newly Broken Tests:
-----------------
org.pentaho.agilebi.modeler.models.annotations.ModelAnnotationGroupXmlWriterTest.testGetXmlWithAnnotations: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<...rty><property><name>[description</name><value>some description</value></property><property><name>aggregateType</name><value>SUM</value></property></properties></annotation><annotation><name>myName</name><field>col1</field><type>CREATE_MEASURE</type><properties><property><name>formatString</name><value>xxxx]</value></property><...> but was:<...rty><property><name>[hidden</name><value>false</value></property><property><name>description</name><value>some description</value></property><property><name>aggregateType</name><value>SUM</value></property></properties></annotation><annotation><name>myName</name><field>col1</field><type>CREATE_MEASURE</type><properties><property><name>formatString</name><value>xxxx</value></property><property><name>hidden</name><value>false]</value></property><...>
	at org.pentaho.agilebi.modeler.models.annotations.ModelAnnotationGroupXmlWriterTest.testGetXmlWithAnnotations(ModelAnnotationGroupXmlWriterTest.java:84)

```
org.pentaho.agilebi.modeler.models.annotations.SharedDimensionGroupCompatibilityTest.testSalesCustomerDimension: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<4> but was:<5>
	at org.pentaho.agilebi.modeler.models.annotations.SharedDimensionGroupCompatibilityTest.testSalesCustomerDimension(SharedDimensionGroupCompatibilityTest.java:106)

```
org.pentaho.agilebi.modeler.models.annotations.SharedDimensionGroupCompatibilityTest.testLoadProductDimension: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<4> but was:<5>
	at org.pentaho.agilebi.modeler.models.annotations.SharedDimensionGroupCompatibilityTest.testLoadProductDimension(SharedDimensionGroupCompatibilityTest.java:87)

```
org.pentaho.agilebi.modeler.models.annotations.SharedDimensionGroupCompatibilityTest.testLoadGeoGroup: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<5> but was:<6>
	at org.pentaho.agilebi.modeler.models.annotations.SharedDimensionGroupCompatibilityTest.testLoadGeoGroup(SharedDimensionGroupCompatibilityTest.java:75)

```
org.pentaho.agilebi.modeler.models.annotations.SharedDimensionGroupCompatibilityTest.testLoadCustomerDimension: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<5> but was:<6>
	at org.pentaho.agilebi.modeler.models.annotations.SharedDimensionGroupCompatibilityTest.testLoadCustomerDimension(SharedDimensionGroupCompatibilityTest.java:40)

```
org.pentaho.agilebi.modeler.models.annotations.SharedDimensionGroupCompatibilityTest.testLoadStateGroup: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<4> but was:<5>
	at org.pentaho.agilebi.modeler.models.annotations.SharedDimensionGroupCompatibilityTest.testLoadStateGroup(SharedDimensionGroupCompatibilityTest.java:124)

```
org.pentaho.agilebi.modeler.models.annotations.SharedDimensionGroupCompatibilityTest.testLoadTeams: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<4> but was:<5>
	at org.pentaho.agilebi.modeler.models.annotations.SharedDimensionGroupCompatibilityTest.testLoadTeams(SharedDimensionGroupCompatibilityTest.java:137)

```
org.pentaho.agilebi.modeler.models.annotations.SharedDimensionGroupCompatibilityTest.testLoadDateDimension: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<6> but was:<7>
	at org.pentaho.agilebi.modeler.models.annotations.SharedDimensionGroupCompatibilityTest.testLoadDateDimension(SharedDimensionGroupCompatibilityTest.java:57)

```
org.pentaho.agilebi.modeler.models.annotations.ModelPropertyTest.testMeasure: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<9> but was:<8>
	at org.pentaho.agilebi.modeler.models.annotations.ModelPropertyTest.testMeasure(ModelPropertyTest.java:43)

```
org.pentaho.agilebi.modeler.models.annotations.ModelAnnotationGroupCompatibilityIT.testLoadCustomerAndPrice: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<4> but was:<5>
	at org.pentaho.agilebi.modeler.models.annotations.ModelAnnotationGroupCompatibilityIT.testLoadCustomerAndPrice(ModelAnnotationGroupCompatibilityIT.java:132)

```
org.pentaho.agilebi.modeler.models.annotations.ModelAnnotationGroupCompatibilityIT.testLoadDimensionTeam: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<3> but was:<4>
	at org.pentaho.agilebi.modeler.models.annotations.ModelAnnotationGroupCompatibilityIT.testLoadDimensionTeam(ModelAnnotationGroupCompatibilityIT.java:86)

```
org.pentaho.agilebi.modeler.models.annotations.AnnotationTypeTest.testIterateProperties: junit.framework.AssertionFailedError
```
junit.framework.AssertionFailedError: expected:<3> but was:<4>
	at org.pentaho.agilebi.modeler.models.annotations.AnnotationTypeTest.testIterateProperties(AnnotationTypeTest.java:131)

```





Unit test coverage change:
============
org.pentaho.agilebi.modeler.BaseModelerWorkspaceHelper:
 * instructionPercentCoverageChange : +0.24%
 * linePercentCoverageChange : +0.24%
    
org.pentaho.agilebi.modeler.models.annotations.CreateMeasure:
 * instructionPercentCoverageChange : +0.34%
 * linePercentCoverageChange : +0.63%
 * complexityPercentCoverageChange : +0.72%
 * methodPercentCoverageChange : +0.39%
    
org.pentaho.agilebi.modeler.models.annotations.AnnotationType:
 * instructionPercentCoverageChange : +0.78%
 * branchPercentCoverageChange : +0.54%
 * linePercentCoverageChange : +0.81%
 * complexityPercentCoverageChange : +0.82%
    
org.pentaho.agilebi.modeler.models.annotations.CreateAttribute:
 * instructionPercentCoverageChange : +0.73%
 * linePercentCoverageChange : +0.92%
 * complexityPercentCoverageChange : +1.15%
 * methodPercentCoverageChange : +0.78%
    
org.pentaho.agilebi.modeler.nodes.BaseColumnBackedMetaData:
 * instructionPercentCoverageChange : +0.91%
 * linePercentCoverageChange : +1.43%
 * complexityPercentCoverageChange : +2.27%
 * methodPercentCoverageChange : +3.32%
    
Integration test coverage change:
============
org.pentaho.agilebi.modeler.BaseModelerWorkspaceHelper:
 * instructionPercentCoverageChange : +0.12%
 * linePercentCoverageChange : +0.12%
    
org.pentaho.agilebi.modeler.models.annotations.CreateMeasure:
 * instructionPercentCoverageChange : +0.98%
 * linePercentCoverageChange : +1.65%
 * complexityPercentCoverageChange : +1.89%
 * methodPercentCoverageChange : +1.96%
    
org.pentaho.agilebi.modeler.models.annotations.CreateAttribute:
 * instructionPercentCoverageChange : +0.12%
 * linePercentCoverageChange : +0.23%
 * complexityPercentCoverageChange : +0.30%
 * methodPercentCoverageChange : +0.26%
    
org.pentaho.agilebi.modeler.nodes.BaseColumnBackedMetaData:
 * instructionPercentCoverageChange : +0.38%
 * linePercentCoverageChange : +0.63%
 * complexityPercentCoverageChange : +1.61%
 * methodPercentCoverageChange : +1.96%

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. rm -r ~/.kettle; rm -r ~/.pentaho; echo removed hidden folders
2. ant -Dpentaho.coding.standards.version=1.0.1 -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove

Changed files:
==============
  src/org/pentaho/agilebi/modeler/BaseModelerWorkspaceHelper.java
  src/org/pentaho/agilebi/modeler/models/annotations/CreateAttribute.java
  src/org/pentaho/agilebi/modeler/models/annotations/CreateMeasure.java
  src/org/pentaho/agilebi/modeler/nodes/BaseColumnBackedMetaData.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/AnnotationTypeTest.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/CreateAttributeIT.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/CreateMeasureTest.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotationGroupCompatibilityIT.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotationGroupXmlWriterTest.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/ModelPropertyTest.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/SharedDimensionGroupCompatibilityTest.java



License header violations:
==========================

1. test-src/org/pentaho/agilebi/modeler/models/annotations/AnnotationTypeTest.java

2. test-src/org/pentaho/agilebi/modeler/models/annotations/ModelAnnotationGroupCompatibilityIT.java

3. test-src/org/pentaho/agilebi/modeler/models/annotations/SharedDimensionGroupCompatibilityTest.java








Unit test coverage change:
============
org.pentaho.agilebi.modeler.BaseModelerWorkspaceHelper:
 * instructionPercentCoverageChange : +0.24%
 * linePercentCoverageChange : +0.24%
    
org.pentaho.agilebi.modeler.models.annotations.CreateMeasure:
 * instructionPercentCoverageChange : +0.34%
 * linePercentCoverageChange : +0.63%
 * complexityPercentCoverageChange : +0.72%
 * methodPercentCoverageChange : +0.39%
    
org.pentaho.agilebi.modeler.models.annotations.AnnotationType:
 * instructionPercentCoverageChange : +0.78%
 * branchPercentCoverageChange : +0.54%
 * linePercentCoverageChange : +0.81%
 * complexityPercentCoverageChange : +0.82%
    
org.pentaho.agilebi.modeler.models.annotations.CreateAttribute:
 * instructionPercentCoverageChange : +0.73%
 * linePercentCoverageChange : +0.92%
 * complexityPercentCoverageChange : +1.15%
 * methodPercentCoverageChange : +0.78%
    
org.pentaho.agilebi.modeler.nodes.BaseColumnBackedMetaData:
 * instructionPercentCoverageChange : +0.91%
 * linePercentCoverageChange : +1.43%
 * complexityPercentCoverageChange : +2.27%
 * methodPercentCoverageChange : +3.32%
    
Integration test coverage change:
============
org.pentaho.agilebi.modeler.BaseModelerWorkspaceHelper:
 * instructionPercentCoverageChange : +0.12%
 * linePercentCoverageChange : +0.12%
    
org.pentaho.agilebi.modeler.models.annotations.CreateMeasure:
 * instructionPercentCoverageChange : +0.98%
 * linePercentCoverageChange : +1.65%
 * complexityPercentCoverageChange : +1.89%
 * methodPercentCoverageChange : +1.96%
    
org.pentaho.agilebi.modeler.models.annotations.CreateAttribute:
 * instructionPercentCoverageChange : +0.12%
 * linePercentCoverageChange : +0.23%
 * complexityPercentCoverageChange : +0.30%
 * methodPercentCoverageChange : +0.26%
    
org.pentaho.agilebi.modeler.nodes.BaseColumnBackedMetaData:
 * instructionPercentCoverageChange : +0.38%
 * linePercentCoverageChange : +0.63%
 * complexityPercentCoverageChange : +1.61%
 * methodPercentCoverageChange : +1.96%

**Pull request merged**
