### PR TITLE
[BACKLOG-2364] Override equals() in ModelAnnotation models

### PR DESCRIPTION
**Pull request by bytekast**

### CODE REVIEW

**Comment by bytekast** [comment]
@kurtwalker @pamval @tgf - please review

**Comment by kurtwalker** [comment]
@bytekast we should be able to write tests for these.

**Comment by bytekast** [comment]
I have tests in the data-refinery project… waiting to issue the pull request until this is merged

**Comment by kurtwalker** [comment]
I'd rather have them here or in both if you can.

**Comment by kurtwalker** [comment]
Thanks.

**Comment by bytekast** [comment]
@kurtwalker you are quick sir

**Pull request merged**
