### PR TITLE
[TEST] Backwards compatibility tests

### PR DESCRIPTION
**Pull request by bytekast**

### CODE REVIEW

**Comment by bytekast** [comment]
@kurtwalker @pminutillo @DFieldFL - please review.

I am going to start writing compatibility tests against the 5.4 branch. Then merge them to master at some point and resolve migration issues.

**Comment by pminutillo** [comment]
:star:

**Comment by DFieldFL** [comment]
Looks good

**Comment by bytekast** [comment]
@pminutillo @DFieldFL - since @kurtwalker is on vacation, please merge

**Pull request merged**
