### PR TITLE
[BACKLOG-6585] - adding ability to set format strings to UpdateAttrib…

### PR DESCRIPTION
**Pull request by kurtwalker**
…ute inline annotation

### CODE REVIEW

**Comment by brosander** [comment]
http://wingman.pentaho.com:8080/job/wingman/56/

**Comment by brosander** [comment]
http://wingman.pentaho.com:8080/job/wingman/57/

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  src/org/pentaho/agilebi/modeler/models/annotations/UpdateAttribute.java
  src/org/pentaho/agilebi/modeler/models/annotations/util/AnnotationConstants.java
  src/org/pentaho/agilebi/modeler/models/annotations/util/MondrianSchemaHandler.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/AnnotationUtil.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/UpdateAttributeTest.java



Unit test coverage change:
============
org.pentaho.agilebi.modeler.models.annotations.UpdateAttribute:
 * Branch Change :  + 2.86%
 * Complexity Change :  + 1.40%
 * Instruction Change :  + .39%
 * Line Change :  + .92%
 * Method Change :  + .62%

org.pentaho.agilebi.modeler.models.annotations.util.MondrianSchemaHandler:
 * Branch Change : **-5.27%**
 * Complexity Change : **-7.94%**
 * Instruction Change : **-.99%**
 * Line Change : **-1.06%**



Integration test coverage change:
============
org.pentaho.agilebi.modeler.models.annotations.util.MondrianSchemaHandler:
 * Branch Change : **-9.97%**
 * Complexity Change : **-8.62%**
 * Instruction Change : **-8.01%**
 * Line Change : **-9.64%**
 * Method Change : **-8.33%**



Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/test-src/org/pentaho/agilebi/modeler/models/annotations/AnnotationUtil.java

1. Message: Using a static member import should be avoided - java.lang.String.format. at Line: 45
2. Message: Using a static member import should be avoided - javax.xml.xpath.XPathConstants.NODE. at Line: 46

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. ant -Dtestreports.dir=bin/reports/unit-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml clean-all resolve jacoco && ant -Dpentaho.coding.standards.version=1.0.4 -Dtestreports.dir=bin/reports/integration-test -Djunit.jvmargs=-XX:PermSize=256m -f build.xml jacoco-integration checkstyle publish-local

Cleanup:
-------
rm -r ~/.ivy2/local || echo no publish local to remove



Changed files:
==============
  src/org/pentaho/agilebi/modeler/models/annotations/UpdateAttribute.java
  src/org/pentaho/agilebi/modeler/models/annotations/util/AnnotationConstants.java
  src/org/pentaho/agilebi/modeler/models/annotations/util/MondrianSchemaHandler.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/AnnotationUtil.java
  test-src/org/pentaho/agilebi/modeler/models/annotations/UpdateAttributeTest.java



Unit test coverage change:
============
org.pentaho.agilebi.modeler.models.annotations.UpdateAttribute:
 * Branch Change :  + 2.86%
 * Complexity Change :  + 1.40%
 * Instruction Change :  + .39%
 * Line Change :  + .92%
 * Method Change :  + .62%

org.pentaho.agilebi.modeler.models.annotations.util.MondrianSchemaHandler:
 * Branch Change : **-5.27%**
 * Complexity Change : **-7.94%**
 * Instruction Change : **-.99%**
 * Line Change : **-1.06%**



Integration test coverage change:
============
org.pentaho.agilebi.modeler.models.annotations.util.MondrianSchemaHandler:
 * Branch Change : **-9.97%**
 * Complexity Change : **-8.62%**
 * Instruction Change : **-8.01%**
 * Line Change : **-9.64%**
 * Method Change : **-8.33%**



Checkstyle violations:
======================
See: https://github.com/pentaho/pentaho-coding-standards
File /home/buildguy/project/test-src/org/pentaho/agilebi/modeler/models/annotations/AnnotationUtil.java

1. Message: Using a static member import should be avoided - java.lang.String.format. at Line: 45
2. Message: Using a static member import should be avoided - javax.xml.xpath.XPathConstants.NODE. at Line: 46

**Comment by kurtwalker** [comment]
@DFieldFL @pminutillo @rfellows please review

**Pull request merged**
